---
url: http://rubini.us
safe: true
lsi: false
permalink: pretty
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - drafts
markdown: rdiscount
highlighter: pygments 
port: 9876

gems: ['bootstrap-sass']
