---
url: http://rubini.us
safe: false 
lsi: false
permalink: pretty
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
  - drafts
markdown: kramdown 
highlighter: pygments 
port: 9876
sass:
  style: :compressed
